name: GHOST_FINAL_STRIKE
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev \
            libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev build-essential \
            libltdl-dev libjpeg-dev libpng-dev
          pip install --user --upgrade "Cython<3.0" buildozer

      - name: Hard Reset and Build
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Полная зачистка кэша, чтобы убить 18 МБ билд
          rm -rf ~/.buildozer
          rm -rf .buildozer
          # Принудительная чистка перед стартом
          buildozer android clean
          buildozer -v android debug

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: Ghost-PRO-Final
          path: bin/*.apk
