name: GHOST_PRO_BETA
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Tools
        run: |
          pip install flet pyrebase4 cryptography requests
          echo "flet" > requirements.txt
          echo "pyrebase4" >> requirements.txt
          echo "cryptography" >> requirements.txt
          echo "requests" >> requirements.txt

      - name: Build Android APK
        run: |
          # Собираем с принудительным включением зависимостей
          flet build apk --project "Ghost PRO" --yes
            
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Ghost-PRO-Full-Pack
          path: build/apk/*.apk
