name: GHOST_PRO_FINAL_BUILD
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Flet Build Tools
        run: |
          pip install flet pyrebase4 cryptography requests
          # Создаем файл зависимостей для сборщика
          echo "flet" > requirements.txt
          echo "pyrebase4" >> requirements.txt
          echo "cryptography" >> requirements.txt
          echo "requests" >> requirements.txt

      - name: Build Android APK
        run: |
          # Указываем активы и принудительно ставим зависимости
          flet build apk \
            --project "Ghost PRO" \
            --include-ext-packages flet,pyrebase4,cryptography,requests \
            --assets ./assets \
            --yes

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: Ghost-PRO-Final-Build
          path: build/apk/*.apk
