name: GHOST_PRO_CORE_2026
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install System
        run: |
          sudo apt update
          sudo apt install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev build-essential
          # Ставим конкретные версии для стабильности 2026 года
          pip install --user --upgrade pip "Cython<3.0" "buildozer>=1.5.0"
      - name: Force Build With Full Libs
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Прямая команда на сборку без использования битого кэша
          buildozer android debug
        env:
          BUILDOZER_ALLOW_ORG_GHOST: 1
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: GhostPRO_Final_Build
          path: bin/*.apk
