name: GHOST_PRO_ULTRA_BUILD
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install All Dependencies
        run: |
          pip install flet pyrebase4 cryptography requests
          # Создаем файл зависимостей принудительно
          echo "flet" > requirements.txt
          echo "pyrebase4" >> requirements.txt
          echo "cryptography" >> requirements.txt
          echo "requests" >> requirements.txt

      - name: Build Heavy APK
        run: |
          # Используем базовую команду без лишних флагов
          flet build apk --project "Ghost PRO" --yes
            
      - name: Upload Final APK
        uses: actions/upload-artifact@v4
        with:
          name: Ghost-PRO-Final-Test
          path: build/apk/*.apk
