name: GHOST_PRO_FINAL_BUILD
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev \
            libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev build-essential \
            libltdl-dev libjpeg-dev libpng-dev
          pip install --user --no-cache-dir --upgrade buildozer cython

      - name: Clean and Force Build
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Удаляем старые следы 19.4 МБ билда
          rm -rf .buildozer
          rm -rf ~/.buildozer
          # Собираем с нуля
          buildozer -v android debug

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: Ghost-PRO-Real-Package
          path: bin/*.apk
